orderApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static

from .views import IndexView, AboutView

urlpatterns = [
    path('restoran/', include('restoran.urls', namespace='restoran')),
    path('', IndexView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restoran/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import static

from .views import (
    LoginView,
    IndexChefView,
    IndexCustomerView,
    AddMenuView
)
app_name = 'restoran'
urlpatterns = [
    path('addmenu/', AddMenuView.as_view(), name='addmenu'),
    path('customer/', IndexCustomerView.as_view(), name='customer'),
    path('chef/', IndexChefView.as_view(), name='chef'),
    path('login/', LoginView.as_view(), name='login'),
]

restoran/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.


class MenuRestoran(models.Model):
    name_menu = models.CharField(max_length=200)
    category_menu = models.CharField(max_length=200)
    image_menu = models.ImageField(null=True, blank=True, upload_to='media')
    price_menu = models.DecimalField(max_digits=6, decimal_places=0)
    slug = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(f"{self.name_menu}")
        super().save()

    def get_absolute_url(self):
        return reverse('restoran:chef')

    def __str__(self):
        return "{}. {}".format(self.id, self.name_menu)

restoran/forms.py
from django import forms

from .models import MenuRestoran


class MenuRestoranForm(forms.ModelForm):
    class Meta:
        model = MenuRestoran
        fields = (
            'name_menu',
            'category_menu',
            'image_menu',
            'price_menu',
        )

orderApp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = {
            'page_title': 'Homepage'
        }
        return context


class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, *args, **kwargs):
        context = {
            'page_title': 'About'
        }
        return context

restoran/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from django.contrib.auth.models import Group
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import user_passes_test
from .models import MenuRestoran
from .forms import MenuRestoranForm
# Create your views here.


class LoginView(TemplateView):
    template_name = 'login.html'

    def post(self, request):
        username_login = request.POST['username']
        password_login = request.POST['password']

        user = authenticate(request, username=username_login,
                            password=password_login)
        if user.groups.filter(name='chef').exists() is True:
            login(request, user)
            return redirect('restoran:chef')
        elif user.groups.filter(name='customer').exists() is True:
            login(request, user)
            return redirect('restoran:customer')
        else:
            return redirect('restoran:login')
        return render(request, 'login.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "LOGIN"
        return context


class AddMenuView(CreateView):
    model = MenuRestoran
    form_class = MenuRestoranForm
    template_name = "restoran/add_menu.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Tambah Menu'
        # print(fields)
        return context


class IndexChefView(ListView):
    model = MenuRestoran
    print()
    # paginate_by = 4

    # def get_context_data(self, *args, **kwargs):
    #     kwargs = self.kwargs
    #     return super().get_context_data(*args, **kwargs)


class IndexCustomerView(TemplateView):
    template_name = "restoran/index_customer.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "HALAMAN CUSTOMER"
        return context

restoran/templates/restoran/add_menu.html
{% extends "base.html" %}

{% block page_title %}
  {{page_title}}
{% endblock page_title %}

{% block contents %}
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'restoran:chef' %}">Order App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'restoran:chef' %}">Menu</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'restoran:chef' %}">Ordering</a>
          </li>
        </ul>
      </div>
      <h6 class="nav navbar-nav navbar-right">Hallo, <b>{{user}}</b></h6>
      <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
          <a class="btn btn-outline-info" href="{% url 'restoran:login' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  <h1>{{page_title}}</h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{form.name_menu.id_for_label}}">{{form.name_menu.label}}:</label>
        <input type="text" class="form-control" name="{{form.name_menu.name}}" maxlength="{{form.name_menu.max}}" required id="{{form.name_menu.id_for_label}}">    
    </div>

    <div class="form-group">
      <label for="{{form.category_menu.id_for_label}}">{{form.category_menu.label}}:</label>
      <input type="text" class="form-control" name="{{form.category_menu.name}}" maxlength="{{form.category_menu.max}}" required id="{{form.category_menu.id_for_label}}">
    </div>

    <!-- <div class="form-group">
        <label for="{{form.image_menu.id_for_label}}">Gambar Menu : </label>
        <input type="file" name="{{form.image_menu.name}}">
    </div> -->

    <div class="form-group">
        <label for="{{form.price_menu.id_for_label}}">{{form.price_menu.label}}:</label>
        <input type="text" class="form-control" name="{{form.price_menu.name}}" maxlength="{{form.price_menu.max}}" required id="{{form.price_menu.id_for_label}}">    
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Tambah</button>
    <a class="btn btn-danger" href="{% url 'restoran:chef' %}">Batal</a>
  </form>
</div>
{% endblock contents %}

restoran/templates/restoran/index.customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_title}}</title>
</head>
<body>
    <h1>{{page_title}}</h1>
</body>
</html>

restoran/templates/restoran/index_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_title}}</title>
</head>
<body>
    <h1>{{page_title}}</h1>
    <h3>{{user}}</h3>
</body>
</html>

restoran/templates/restoran/menurestoran_form.html
{% extends "base.html" %}

{% block page_title %}
  {{page_title}}
{% endblock page_title %}

{% block contents %}
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'restoran:chef' %}">Order App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'restoran:chef' %}">Menu</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'restoran:chef' %}">Ordering</a>
          </li>
        </ul>
      </div>
      <h6 class="nav navbar-nav navbar-right">Hallo, <b>{{user}}</b></h6>
      <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
          <a class="btn btn-outline-info" href="{% url 'restoran:login' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  <h1>{{page_title}}</h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{form.name_menu.id_for_label}}">{{form.name_menu.label}}:</label>
        <input type="text" class="form-control" name="{{form.name_menu.name}}" maxlength="{{form.name_menu.max}}" required id="{{form.name_menu.id_for_label}}">    
    </div>

    <div class="form-group">
      <label for="{{form.category_menu.id_for_label}}">{{form.category_menu.label}}:</label>
      <input type="text" class="form-control" name="{{form.category_menu.name}}" maxlength="{{form.category_menu.max}}" required id="{{form.category_menu.id_for_label}}">
    </div>

    <div class="form-group">
        <label for="{{field.auto_id}}">{{field.label}} </label>
        <input type="file" name="{{form.image_menu.name}}">
    </div>

    <div class="form-group">
        <label for="{{form.price_menu.id_for_label}}">{{form.price_menu.label}}:</label>
        <input type="text" class="form-control" name="{{form.price_menu.name}}" maxlength="{{form.price_menu.max}}" required id="{{form.price_menu.id_for_label}}">    
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Tambah</button>
    <a class="btn btn-danger" href="{% url 'restoran:chef' %}">Batal</a>
  </form>
</div>
{% endblock contents %}

restoran/templates/restoran/menurestoran_list.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
  {{page_title}}
{% endblock page_title %}

{% block contents %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'restoran:chef' %}">Order App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'restoran:chef' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'restoran:chef' %}">Ordering</a>
              </li>
            </ul>
          </div>
          <h6 class="nav navbar-nav navbar-right">Hallo, <b>{{user}}</b></h6>
          <ul class="nav navbar-nav navbar-right">
              <li class="nav-item">
              <a class="btn btn-outline-info" href="{% url 'restoran:login' %}">Logout</a>
            </li>
          </ul>
        </div>
      </nav>
      <a class="btn btn-primary mt-3" href="{% url 'restoran:addmenu' %}" style="margin-left: 42px;">Add Menu</a>
      <div class="container">
          <ul class="mt-3">
            {% for menu in object_list %}
              <div class="card float-left ml-3" style="width: 15rem; height: 22rem">
                
                {% if menu.image_menu %}
                  <img class="card-img-top mx-auto mt-2 " src="{{menu.image_menu.url}}" alt="{{menu.image_menu}}" style="width: 10rem; height:10rem">
                {% else %}
                  <img class="card-img-top mx-auto mt-2 " src="{% static 'img/default.png' %}" alt="{{menu.image_menu}}" style="width: 10rem; height:10rem">
                {% endif %}
                  
                <div class="card-body">
                  <h3 class="card-text text-center">{{menu.name_menu}}</h3>
                  <div class="container mt-2">
                    <img src="/static/img/pricetag.svg" style="width:20px; height:20px">
                    <span class="text-danger text-center font-weight-bold">{{menu.price_menu}}</span>
                  </div>
                  <a class="badge bg-warning" href=""><span class="oi" data-glyph="icon-name" title="icon name" aria-hidden="true"><img src="/static/img/edit.svg" alt=""></a>
                  <a class="badge bg-danger mt-3" href=""><span class="oi" data-glyph="icon-name" title="icon name" aria-hidden="true"><img src="/static/img/delete.svg" alt=""></a>
                </div>
              </div>
            {% endfor %}
          </ul>
      </div>
{% endblock contents %}

templates/about.html
{% extends "base.html" %}

{% block page_title %}
  {{page_title}}
{% endblock page_title %}

{% block contents %}
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Order App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
          </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
            <a class="btn btn-outline-info" href="{% url 'restoran:login' %}">Login</a>
          </li>
        </ul>
      </div>
    </nav>
      <div class="container">
        <h2>About</h2>
        <img src="../static/bootstrap/img/renaleki.png"  class="rounded-circle" alt="" style="width: 200px; height:200px">
        <table class="table mt-3">
          <tbody>
            <tr>
              <th scope="row">Name Lengkap</th>
              <td>Renal Eki Riyanto</td>
            </tr>
            <tr>
              <th scope="row">No. BP</th>
              <td>17101152620039</td>
            </tr>
            <tr>
              <th scope="row">Kelas</th>
              <td>SK-1</td>
            </tr>
            <tr>
              <th scope="row">Jurusan</th>
              <td>Sistem Komputer</td>
            </tr>
            <tr>
              <th scope="row">Fakultas</th>
              <td>Ilmu Komputer</td>
            </tr>
            <tr>
              <th scope="row">Judul Skripsi</th>
              <td>Perancangan dan Bangun Miniatur Sistem Pemesanan Menu Restoran Berbasis Website Python Django dengan Raspberry Pi</td>
            </tr>
            <tr>
              <th scope="row">Perguruan Tinggi</th>
              <td>Universitas Putra Indonesia YPTK Padang</td>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
{% endblock contents %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    
    {% block tambahan_css %}
      
    {% endblock tambahan_css %}
    <title>
        {% block page_title %}
          
        {% endblock page_title %}
    </title>
  </head>
  <body>
    {% block contents %}
      
    {% endblock contents %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'bootstrap/bootstrap.js' %}"></script>
    {% block tambahan_js %}
      
    {% endblock tambahan_js %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block page_title %}
  {{page_title}}
{% endblock page_title %}

{% block contents %}
  <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Order App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
              </ul>
            </div>
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item">
                <a class="btn btn-outline-info" href="{% url 'restoran:login' %}">Login</a>
              </li>
            </ul>
          </div>
        </nav>
      <div class="container text-center">
            <h1>Welcome to Website</h1>
            <h3>RENAL EKI RIYANTO</h3>
            <a class="btn btn-dark mt-5" href="{% url 'about' %}">MORE</a>
      </div>
  </div>
{% endblock contents %}

templates/login.html
{% extends "base.html" %}

{% block tambahan_css %}
    <link rel="stylesheet" href="../templates/login_style.css">
{% endblock tambahan_css %}

{% block page_title %}
  {{page_title}}
{% endblock page_title %}

{% block contents %}
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card my-5" style="height:292px">
            <div class="card-body shadow p-3 mb-5 bg-white rounded">
                <h5 class="card-title text-center">{{page_title}}</h5>
                <form style="width:100%" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="username" class="form-label">Username</label>
                      <input type="text" class="form-control" name="username" id="username">
                    </div>
                    <div class="mb-3">
                      <label for="password" class="form-label">Password</label>
                      <input type="password" class="form-control" name="password" id="password">
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}